site_name: 👾 DESMA126 Game Engine
theme: 
  name: simple-blog
  sidebar: true
  navigation_depth: 2
  components:
    title: false
    preview: true
  theme_style: light
extra_css:
  - extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
nav:
  - 🏠 Home: index.md
  - 📜 Syllabus: syllabus.md
  - 📅 Schedule: schedule.md 
  - 📌 Assignments:
    - How To Submit: how-to-submit.md
    - Survey: survey.md
    - Readings & Homeplays: readings-and-homeplays.md
    - Project 1: project-1.md
    - Project 2: project-2.md
    - Project 3: project-3.md
plugins:
  - exclude:
      glob:
        - '13-inventory-database.md'
